ASSUME CS:CODE,DS:DATA
DATA SEGMENT
String DB 'BMS COLLEGE'
Length EQU ($-String)
Key DB 'X'
Dis1 DB '-IS PRESENT IN GIVEN STRING$'
Dis2 DB '-IS NOT PRESENT IN GIVEN STRING$'
DATA ENDS
CODE SEGMENT
START:
MOV AX,DATA
MOV DS, AX
MOV ES, AX
MOV DL, Key
MOV AH, 02h
INT 21h
LEA DI, String
MOV AL, Key
MOV CX, Length
REPNE SCASB
JE PRESENT
LEA DX, Dis2
CALL Display
JMP OVER
PRESENT: LEA DX, Dis1
CALL Display
OVER: MOV AH, 4Ch
INT 21h
Display PROC NEAR
MOV AH, 09h
INT 21h
RET
Display ENDP
CODE ENDS
END START